# -*- coding: utf-8 -*-
"""SSH Map example plugin — the Maintenance Check (TWO facts, ONE command).

This file is an EXAMPLE, not a shipped plugin (see `examples/README.md`): copy it into
`~/.sshmap/plugins/` and use "Plugins → Reload". It answers the two questions a fleet asks — "does
this host wait for a reboot?" and "are updates pending?" — and its lesson is that they travel as ONE
command with a MARKER protocol: `ctx.run_command()` opens a connection per node PER CALL.

`run_on_nodes(nodes, ctx)` COLLECTS with ONE generated POSIX-sh probe per node, gathering `F|` /
`U|` / `R|` evidence and ending with `PROBE_MARKER` (an answer without it is caught, never guessed
at); `status_probe(node)` REPORTS the cached verdict and composes the detail itself ("reboot
required · 12 updates") — an unknown family gets NO update verdict, and `timeout=` is passed
because a package manager on a slow mirror outlives the shipped per-node budget."""

import json
import os
import tempfile
import time
from typing import Dict, Optional

MANIFEST = {
    "name": "maintenance",
    "version": "1.0",
    "api_version": 1,
    "description": "Reports a pending reboot and pending updates from ONE probe per server",
}

PROBE_MARKER = "M|end"
REBOOT_FILE = "/var/run/reboot-required"
DEB_FAMILY = "deb"
RPM_FAMILY = "rpm"
FAMILIES = (DEB_FAMILY, RPM_FAMILY)
DETAIL_SEPARATOR = " \u00b7 "
PROBE_TIMEOUT_S = 120.0     # a package manager on a slow mirror owns the whole per-node budget
CACHE_NAME = "maintenance.state.json"
CACHE_VERSION = 1
STALE_SECONDS = 21600       # two status rounds is a hint, half a day is the honest life of one
MAX_RECORDS = 50
UPDATES_NONE = "none"
UPDATES_AVAILABLE = "available"
UPDATES_UNKNOWN = "unknown"


# ── the probe: ONE script, TWO facts, a marker at the end ─────────────────────────
# The RPM family asks `dnf -q check-update` for a VERDICT only (exit 100 = updates available,
# 0 = none) while the DEB family can count them — so the evidence carries both shapes and the
# reader is the one place that knows the difference. Nothing is interpolated into the script:
# it is generated by the plugin, never by the answer.

def build_probe_script() -> str:
    """The ONE POSIX-sh probe: collect the family, the pending updates and the reboot verdict."""
    return "\n".join((
        "# sshmap maintenance — evidence only; the reader is `parse_evidence()`.",
        "F=unknown",
        "U=" + UPDATES_UNKNOWN,
        "if command -v apt-get >/dev/null 2>&1; then",
        "  F=" + DEB_FAMILY,
        "  U=$(apt-get -s upgrade 2>/dev/null | grep -c '^Inst ')",
        "elif command -v dnf >/dev/null 2>&1; then",
        "  F=" + RPM_FAMILY,
        "  dnf -q check-update >/dev/null 2>&1",
        "  rc=$?",
        '  if [ "$rc" = "0" ]; then U=' + UPDATES_NONE + "; "
        'elif [ "$rc" = "100" ]; then U=' + UPDATES_AVAILABLE + "; fi",
        "elif command -v yum >/dev/null 2>&1; then",
        "  F=" + RPM_FAMILY,
        "  yum -q check-update >/dev/null 2>&1",
        "  rc=$?",
        '  if [ "$rc" = "0" ]; then U=' + UPDATES_NONE + "; "
        'elif [ "$rc" = "100" ]; then U=' + UPDATES_AVAILABLE + "; fi",
        "fi",
        'echo "F|$F"',
        'echo "U|$U"',
        "R=no",
        "if [ -e " + REBOOT_FILE + " ]; then R=yes; fi",
        'echo "R|$R"',
        'if [ "$R" = "no" ] && command -v needs-restarting >/dev/null 2>&1; then',
        "  needs-restarting -r >/dev/null 2>&1",
        "  rc=$?",
        '  if [ "$rc" = "1" ]; then echo "R|yes"; fi',
        "fi",
        'echo "' + PROBE_MARKER + '"',
        "exit 0",
    ))


def probe_completed(text) -> bool:
    """True when the answer carries the END marker (a truncated probe is not a report)."""
    return PROBE_MARKER in str(text or "")


def parse_evidence(text) -> dict:
    """The `F|` / `U|` / `R|` evidence as `{family, reboot, updates}` (unknown is `None`/`""`).

    `family` is `deb` / `rpm` / `""` (no family the plugin knows), `reboot` is True / False / None
    and `updates` is a COUNT (an int), True (updates available, no number), False (none pending) or
    None (no verdict). A `R|` line later in the answer WINS over an earlier "no" — the RPM family
    asks `needs-restarting -r` only after the marker file said no.
    """
    evidence: Dict[str, object] = {"family": "", "reboot": None, "updates": None}
    for raw in str(text or "").splitlines():
        line = raw.strip()
        if "|" not in line:
            continue
        key, _, value = line.partition("|")
        key, value = key.strip().upper(), value.strip()
        if key == "F":
            evidence["family"] = value if value in FAMILIES else ""
        elif key == "R":
            if value == "yes":
                evidence["reboot"] = True
            elif value == "no" and evidence["reboot"] is None:
                evidence["reboot"] = False
        elif key == "U":
            if value == UPDATES_NONE:
                evidence["updates"] = False
            elif value == UPDATES_AVAILABLE:
                evidence["updates"] = True
            elif value.isdigit():
                evidence["updates"] = int(value)
    return evidence


def compose_detail(reboot, updates) -> str:
    """The detail the plugin COMPOSES: `"reboot required · 12 updates"`, `""` for nothing to say.

    An unknown fact contributes nothing (an update verdict the family does not support is never
    guessed at), and "nothing pending" is not part of the sentence — the plugin reports what the
    user has to act on.
    """
    parts = []
    if reboot:
        parts.append("reboot required")
    if updates is True:
        parts.append("updates available")
    elif isinstance(updates, int) and not isinstance(updates, bool) and updates > 0:
        parts.append(f"{updates} update" + ("" if updates == 1 else "s"))
    return DETAIL_SEPARATOR.join(parts)


# ── the cache: the plugin's own data, next to the plugin folder ───────────────────

def cache_path() -> str:
    """`~/.sshmap/plugins/maintenance.state.json` — the plugin's own cache file."""
    return os.path.join(os.path.expanduser("~"), ".sshmap", "plugins", CACHE_NAME)


def _clean_verdict(value) -> object:
    """A stored verdict: True / False / a count / None — anything else is "unknown"."""
    if value is True or value is False or value is None:
        return value
    if isinstance(value, int):
        return max(0, value)
    return None


def _clean_record(record) -> Optional[dict]:
    """One stored record, validated (`None` for junk — a broken entry is dropped, not fatal)."""
    if not isinstance(record, dict):
        return None
    try:
        stamp = float(record.get("ts") or 0.0)
    except (TypeError, ValueError):
        stamp = 0.0
    family = str(record.get("family") or "")
    return {"alias": str(record.get("alias") or ""),
            "family": family if family in FAMILIES else "",
            "reboot": _clean_verdict(record.get("reboot")),
            "updates": _clean_verdict(record.get("updates")), "ts": stamp}


def load_cache() -> Dict[str, dict]:
    """The stored records keyed by node id — `{}` for a missing / broken / foreign cache."""
    try:
        with open(cache_path(), encoding="utf-8") as handle:
            document = json.load(handle)
    except Exception:                       # missing, unreadable, not JSON — all "no cache"
        return {}
    if not isinstance(document, dict) or not isinstance(document.get("records"), dict):
        return {}
    clean: Dict[str, dict] = {}
    for node_id, record in document["records"].items():
        good = _clean_record(record)
        if good is not None:
            clean[str(node_id)] = good
    return clean


def _prune(records: Dict[str, dict]) -> Dict[str, dict]:
    """The `MAX_RECORDS` NEWEST records (a node that left the map must not grow the file)."""
    ordered = sorted(records.items(), key=lambda item: float(item[1].get("ts") or 0.0),
                     reverse=True)
    return dict(ordered[:MAX_RECORDS])


def save_cache(records) -> bool:
    """Merge + prune + write the cache ATOMICALLY (a temp file in the folder + `os.replace`)."""
    if not isinstance(records, dict):
        return False
    merged = load_cache()
    for node_id, record in records.items():
        good = _clean_record(record)
        if good is not None:
            merged[str(node_id)] = good
    document = {"version": CACHE_VERSION, "records": _prune(merged)}
    folder = os.path.dirname(cache_path())
    temp_path = ""
    try:
        os.makedirs(folder, exist_ok=True)
        handle, temp_path = tempfile.mkstemp(prefix=".maintenance-", suffix=".tmp", dir=folder)
        with os.fdopen(handle, "w", encoding="utf-8") as stream:
            json.dump(document, stream, ensure_ascii=False, indent=2)
        os.replace(temp_path, cache_path())
        return True
    except Exception:                       # noqa: BLE001 — a cache is disposable
        if temp_path:
            try:
                os.remove(temp_path)
            except OSError:
                pass
        return False


def fresh_record(node_id, now: Optional[float] = None) -> Optional[dict]:
    """The record of a node, or None when it is unknown, missing or STALE."""
    record = load_cache().get(str(node_id or ""))
    if record is None:
        return None
    moment = time.time() if now is None else float(now)
    if moment - float(record.get("ts") or 0.0) > STALE_SECONDS:
        return None
    return record


# ── the hooks ─────────────────────────────────────────────────────────────────────

def run_on_nodes(nodes, ctx):
    """The COLLECTOR: ONE probe per node (the marker protocol), then ONE cache write."""
    records = list(nodes or [])
    if not records:
        ctx.status("maintenance: nothing selected", 3000)
        return
    collected: Dict[str, dict] = {}
    failures = []

    def on_result(node, result):
        """One node's answer (or its failure) — a failure is a result for THAT node."""
        if result.error or result.exit_code != 0:
            failures.append(node.id)
            ctx.log(f"maintenance: {node.label()} — no answer "
                    f"({result.error or 'exit code ' + str(result.exit_code)})")
            return
        if not probe_completed(result.output):
            failures.append(node.id)
            ctx.log(f"maintenance: {node.label()} — the probe did not finish (no {PROBE_MARKER})")
            return
        evidence = parse_evidence(result.output)
        collected[node.id] = {"alias": node.alias, "family": evidence["family"],
                              "reboot": evidence["reboot"], "updates": evidence["updates"],
                              "ts": time.time()}
        ctx.log(f"maintenance: {node.label()} — "
                f"{compose_detail(evidence['reboot'], evidence['updates']) or 'nothing to do'}")

    def on_finished(results):
        """The whole round: one atomic cache write, then the line the user reads."""
        saved = save_cache(collected) if collected else False
        flagged = [record for record in collected.values()
                   if compose_detail(record["reboot"], record["updates"])]
        ctx.status(f"maintenance: {len(collected)} node(s), {len(flagged)} to act on", 5000)
        if collected and not saved:
            ctx.log("maintenance: the cache could not be written — the card keeps the SSH status")
        if failures:
            ctx.log(f"maintenance: {len(failures)} node(s) without an answer: "
                    f"{', '.join(sorted(failures))}")

    # ONE call for BOTH facts: `ctx.run_command` opens its own connection per node per call, so
    # splitting the questions into two calls would double the connections of every run.
    if not ctx.run_command(records, build_probe_script(), on_result=on_result,
                           on_finished=on_finished, timeout=PROBE_TIMEOUT_S):
        ctx.log("maintenance: run_command() refused the call (no nodes or an empty command)")
        ctx.status("maintenance: nothing to do", 3000)


def status_probe(node):
    """The REPORTER: `("warn", "<the composed detail>")`, or None for "no opinion".

    Reads the cache and NOTHING else (a probe runs for every node on every status round). The
    detail is composed HERE, from the two facts the collector stored, so the card carries the
    sentence the user acts on; nothing to act on is `None`, never an `online` of the plugin's own.
    """
    record = fresh_record(getattr(node, "id", ""))
    if record is None:
        return None
    detail = compose_detail(record["reboot"], record["updates"])
    return ("warn", detail) if detail else None
